apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argocd
  namespace: kube-system
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  version: 4.9.7
  targetNamespace: argocd
  valuesContent: |-
    fullnameOverride: argocd
    dex: {}
    server:  
      config:
        url: https://github.com/its-software-services-customers/p2w-epeagle-addons.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-app
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/its-software-services-customers/p2w-epeagle-addons.git
    targetRevision: '<<ENV>>' #Should be based on environment
    path: 'applications'

  # Destination cluster and namespace to deploy the application
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
---
apiVersion: v1
kind: Secret
metadata:
  name: local-cluster-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    custom: "true"
type: Opaque
stringData:
  name: <<ENV>>
  server: https://notused
  config: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: github-auth-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque    
stringData:
  url: https://github.com/its-software-services-customers/p2w-epeagle-addons.git
  #username: dummy-gh
  #password: 'notused-because-it-is-public'
  type: git
---
# Put it here to make ArgoCD knows the AlertManagerConfig
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-45.15.0
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
